### ISSUE TITLE
Better GUI

### ISSUE THREAD

**Issue by jonaylor89** [jonaylor89/PhysicsAnalysis#6]
The GUI right now is really boring and basic. It would be nice to have one that gives the user the ability to choose which graph they want (position, velocity, acceleration, 2D, 3D) and have the GUI be a lot more pleasing to look at.

**Comment by isman7** [comment]
Ey! I've worked around a little bit but it is not working yet. you have know a Grid Layout with an open file widget. 

You have to work with the matplotlib fully integration. I'll do PR in few minutes. 

Isma

**Comment by jonaylor89** [comment]
I really like it except I want to try and keep the 3D model if at all possible. I'm still going to pull it because you left the GenerateGraph file untouched allowing someone to still get the individual graphs but having the 3D graph in the Grid Layout would be nice. I'd do it but I'm awful at creating GUIs hence the issue.

**Comment by isman7** [comment]
It is ok! I was in a hackaton helping with hacktoberfest. I only have one hour to contribute, let's hope anyone can help a little bit more :+1:

**Comment by isman7** [comment]
I've just checked and I don't know why the 3D plot was not updated. The main issue know is to add the rigth labels in the plots. I don't know why I was getting some errors. I'll pull request again.

**Comment by jonaylor89** [comment]
Thanks
